import streamlit as st
import streamlit.components.v1 as components

st.set_page_config(page_title='간식뺏기 : STEALTH', page_icon='🍪', layout='wide', initial_sidebar_state='collapsed')
st.markdown('''<style>html,body,[data-testid="stAppViewContainer"]{background:#090d14!important}[data-testid="stHeader"],[data-testid="stToolbar"],footer{display:none!important}.block-container{padding:0!important;max-width:100%!important}iframe{width:100%!important;border:0!important}</style>''', unsafe_allow_html=True)

HTML = r'''<!doctype html>
<html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no">
<style>
*{box-sizing:border-box}body{margin:0;background:#090d14;color:#e9eef5;font-family:ui-monospace,SFMono-Regular,Consolas,monospace;overflow:hidden}
#game{position:relative;width:100vw;height:940px;max-height:100vh;background:#111827;overflow:hidden}canvas{display:block;width:100%;height:100%;image-rendering:pixelated}
#hud{position:absolute;left:14px;right:14px;top:12px;display:flex;gap:8px;z-index:5;pointer-events:none}.panel{background:#080d14dd;border:1px solid #657388;padding:8px 10px;box-shadow:0 4px 18px #0007}.mission{flex:1}.stats{min-width:270px}.small{font-size:12px;color:#aeb8c7}.big{font-size:15px;font-weight:800}.bar{height:9px;background:#263040;border:1px solid #536176;margin-top:5px}.fill{height:100%;transition:width .08s linear}.alert{background:#e55}.stam{background:#66c98a}.noise{background:#d6ad55}
#toast{position:absolute;left:50%;top:80px;transform:translateX(-50%);z-index:10;background:#080d14ed;border:1px solid #8997ab;padding:10px 15px;opacity:0;transition:.15s;pointer-events:none;text-align:center}#toast.show{opacity:1}
#controls{position:absolute;bottom:12px;left:14px;right:14px;display:flex;justify-content:space-between;z-index:6;pointer-events:none}#hint{background:#080d14d9;border:1px solid #526078;padding:7px 10px;font-size:11px}#buttons{display:flex;gap:7px;pointer-events:auto}button{font:inherit;color:#eef;background:#141d2a;border:1px solid #60708a;padding:8px 12px;cursor:pointer}button:hover{background:#223047}
#touch{display:none;position:absolute;bottom:65px;left:16px;right:16px;z-index:8;pointer-events:none;justify-content:space-between}.pad{display:grid;grid-template-columns:48px 48px 48px;grid-template-rows:48px 48px 48px;gap:4px;pointer-events:auto}.pad button,.actions button{padding:0;width:48px;height:48px;background:#0b111bdd;border-color:#718099}.pad .up{grid-column:2}.pad .left{grid-column:1;grid-row:2}.pad .down{grid-column:2;grid-row:2}.pad .right{grid-column:3;grid-row:2}.actions{display:flex;gap:6px;align-items:end;pointer-events:auto}
#overlay{position:absolute;inset:0;background:#05080de8;z-index:20;display:flex;align-items:center;justify-content:center;text-align:center;padding:25px}.card{width:min(720px,94%);border:1px solid #77859a;background:#0b111a;padding:28px;box-shadow:0 20px 70px #000}.title{font-size:clamp(30px,5vw,62px);letter-spacing:4px;font-weight:900;margin-bottom:8px}.subtitle{color:#aeb8c7;line-height:1.7}.gold{color:#ffd66b}.red{color:#ff7474}.green{color:#77e0a0}kbd{border:1px solid #69778b;background:#171f2c;padding:2px 6px}.hidden{display:none!important}
@media(max-width:850px){#game{height:100vh;min-height:680px}#touch{display:flex}#hint{max-width:55%;font-size:10px}#buttons{display:none}.stats{min-width:180px}}
</style></head><body><div id="game"><canvas id="c" width="1280" height="900"></canvas>
<div id="hud"><div class="panel mission"><div class="big">🍪 간식뺏기 : STEALTH</div><div id="objective" class="small">목표: 작전 시작</div><div id="mapBadge" class="small">구역: 교실</div></div><div class="panel stats"><div class="small">경계도 <span id="alertText">0%</span></div><div class="bar"><div id="alertFill" class="fill alert"></div></div><div class="small">스태미나 <span id="stamText">100</span></div><div class="bar"><div id="stamFill" class="fill stam"></div></div><div class="small">소음 <span id="noiseText">0</span></div><div class="bar"><div id="noiseFill" class="fill noise"></div></div></div></div>
<div id="toast"></div><div id="controls"><div id="hint">WASD/방향키 이동 · SHIFT 달리기 · SPACE 숨기 · E 상호작용 · ESC 일시정지</div><div id="buttons"><button id="pauseBtn">일시정지</button><button id="restartBtn">처음부터</button></div></div>
<div id="touch"><div class="pad"><button class="up" data-key="ArrowUp">▲</button><button class="left" data-key="ArrowLeft">◀</button><button class="down" data-key="ArrowDown">▼</button><button class="right" data-key="ArrowRight">▶</button></div><div class="actions"><button data-key="Shift">RUN</button><button data-key=" ">HIDE</button><button data-key="e">E</button></div></div>
<div id="overlay"><div class="card"><div id="title" class="title">🍪 STEALTH</div><div id="subtitle" class="subtitle"><span class="gold">VERY HARD</span><br><br>교실 → 복도 → 학생부실에서 <b>정보실 열쇠</b> 획득 → 복도 → 정보실에서 <b>간식</b> 획득 → 교실 귀환.<br><br>선생님 시야, CCTV, 발소리, 잠긴 문, 경보를 모두 피해야 한다.</div><br><button id="startBtn">작전 시작</button><div class="small" style="margin-top:15px">PC: WASD / Shift / Space / E · 모바일: 화면 버튼</div></div></div>
<script>
const C=document.getElementById('c'),X=C.getContext('2d'),W=1280,H=900,K={};let started=false,paused=false,dead=false,won=false,last=0,toastTimer=0,section='교실',alert=0,hasKey=false,hasSnack=false,cd=0;
const P={x:145,y:755,r:13,speed:165,stam:100,hidden:false,noise:0};let checkpoint={x:145,y:755};
const walls=[{x:20,y:110,w:1240,h:25},{x:20,y:830,w:1240,h:25},{x:20,y:110,w:15,h:745},{x:1245,y:110,w:15,h:745},{x:395,y:110,w:25,h:245},{x:395,y:470,w:25,h:385},{x:420,y:405,w:360,h:25},{x:780,y:110,w:25,h:245},{x:780,y:470,w:25,h:385},{x:805,y:405,w:440,h:25},{x:420,y:110,w:360,h:25},{x:805,y:110,w:440,h:25}];
const doors=[{x:395,y:355,w:25,h:115,open:true,name:'교실 문'},{x:780,y:355,w:25,h:115,open:false,name:'학생부실 문'},{x:805,y:355,w:25,h:115,open:false,name:'정보실 문'}];
const obs=[{x:85,y:210,w:100,h:48,t:'desk'},{x:225,y:210,w:100,h:48,t:'desk'},{x:85,y:310,w:100,h:48,t:'desk'},{x:225,y:310,w:100,h:48,t:'desk'},{x:85,y:410,w:100,h:48,t:'desk'},{x:225,y:410,w:100,h:48,t:'desk'},{x:85,y:510,w:100,h:48,t:'desk'},{x:225,y:510,w:100,h:48,t:'desk'},{x:85,y:610,w:100,h:48,t:'desk'},{x:225,y:610,w:100,h:48,t:'desk'},{x:470,y:190,w:245,h:28,t:'locker'},{x:845,y:190,w:310,h:28,t:'locker'},{x:470,y:750,w:245,h:28,t:'bench'},{x:845,y:750,w:310,h:28,t:'bench'},{x:475,y:180,w:110,h:65,t:'desk'},{x:610,y:180,w:110,h:65,t:'desk'},{x:475,y:285,w:245,h:38,t:'cabinet'},{x:840,y:180,w:130,h:60,t:'desk'},{x:1000,y:180,w:150,h:60,t:'desk'},{x:840,y:285,w:310,h:40,t:'cabinet'}];
const G=[{name:'학생부 선생님',x:590,y:145,r:15,angle:1.57,speed:85,fov:1.05,range:285,route:[[590,145],[715,145],[715,330],[590,330],[470,330],[470,145]],i:0,rate:1.25},{name:'복도 순찰',x:460,y:690,r:15,angle:0,speed:105,fov:.82,range:300,route:[[460,690],[760,690],[1120,690],[1120,500],[820,500],[460,500]],i:0,rate:.95},{name:'정보 선생님',x:1010,y:150,r:16,angle:1.57,speed:78,fov:.9,range:360,route:[[1010,150],[1170,150],[1170,350],[1000,350],[850,350],[850,150]],i:0,rate:1.7}];
const CAM=[{x:365,y:145,a:1.57,range:310,fov:.55,spin:.45},{x:1220,y:440,a:3.14,range:300,fov:.6,spin:-.55},{x:800,y:650,a:1.57,range:250,fov:.5,spin:.35}];
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));function d(a,b){return Math.hypot(a.x-b.x,a.y-b.y)}function toast(s,t=1700){let e=document.getElementById('toast');e.textContent=s;e.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>e.classList.remove('show'),t)}
function hit(r,x,y,R){let nx=clamp(x,r.x,r.x+r.w),ny=clamp(y,r.y,r.y+r.h);return (x-nx)**2+(y-ny)**2<R*R}function blocked(x,y,r){for(const q of walls.concat(obs))if(hit(q,x,y,r))return true;for(const q of doors)if(!q.open&&hit(q,x,y,r))return true;return false}function move(o,dx,dy){let nx=o.x+dx;if(!blocked(nx,o.y,o.r))o.x=nx;let ny=o.y+dy;if(!blocked(o.x,ny,o.r))o.y=ny;o.x=clamp(o.x,45,1235);o.y=clamp(o.y,140,820)}
function lineBlocked(x1,y1,x2,y2){for(const q of walls.concat(obs)){for(let i=0;i<=16;i++){let t=i/16,x=x1+(x2-x1)*t,y=y1+(y2-y1)*t;if(x>=q.x&&x<=q.x+q.w&&y>=q.y&&y<=q.y+q.h)return true}}return false}
function sees(s,t,range,fov){let dx=t.x-s.x,dy=t.y-s.y,dist=Math.hypot(dx,dy);if(dist>range)return 0;let a=Math.atan2(dy,dx)-s.angle;while(a>Math.PI)a-=Math.PI*2;while(a<-Math.PI)a+=Math.PI*2;if(Math.abs(a)>fov/2||lineBlocked(s.x,s.y,t.x,t.y))return 0;return 1-(dist/range)*.45}
function objective(){let s=!hasKey?(section==='교실'?'목표: 교실을 빠져나가 복도로 이동':'목표: 학생부실에서 정보실 열쇠를 찾아라'):(!hasSnack?(section==='정보실'?'목표: 정보실에서 간식을 훔쳐라':'목표: 정보실로 이동하라'):'목표: 간식을 들고 교실로 귀환하라!');document.getElementById('objective').textContent=s;document.getElementById('mapBadge').textContent='구역: '+section+(hasKey?' · 🔑 열쇠':'')+(hasSnack?' · 🍪 간식':'')}
function sectionCheck(){let n=P.x<395?'교실':P.x>805&&P.y<405?'정보실':P.x>420&&P.x<780&&P.y<405?'학생부실':'복도';if(n!==section){section=n;toast('▶ '+n);objective()}}
function interact(){if(cd>0)return;cd=.3;if(!hasKey&&P.x>510&&P.x<700&&P.y>260&&P.y<365){hasKey=true;doors[1].open=true;doors[2].open=true;checkpoint={x:730,y:500};toast('🔑 정보실 열쇠 획득! 체크포인트 갱신.',2400);objective();return}if(hasKey&&!hasSnack&&P.x>1030&&P.x<1180&&P.y>260&&P.y<365){hasSnack=true;checkpoint={x:830,y:500};toast('🍪 간식 확보! 이제 들키지 말고 교실로 돌아가라!',2800);objective();return}toast('여기서는 아무것도 할 수 없다.')}
function hide(){if(P.hidden){P.hidden=false;toast('👤 숨기 해제');return}for(const o of obs)if(d(P,{x:o.x+o.w/2,y:o.y+o.h/2})<68){P.hidden=true;P.noise=0;toast('🫥 숨었다.');return}toast('숨을 곳이 가까이 없다.')}
function fail(reason){if(dead||won)return;dead=true;document.getElementById('overlay').classList.remove('hidden');document.getElementById('title').textContent='🚨 발각!';document.getElementById('subtitle').innerHTML='<span class="red">작전 실패</span><br><br>'+reason+'<br><br>체크포인트에서 다시 시작할 수 있다.';document.getElementById('startBtn').textContent='체크포인트에서 재시작'}
function win(){won=true;document.getElementById('overlay').classList.remove('hidden');document.getElementById('title').textContent='🍪 MISSION CLEAR';document.getElementById('subtitle').innerHTML='<span class="green">성공!</span><br><br>간식을 빼앗고 교실까지 무사히 귀환했다.<br>완벽한 잠입이었다.';document.getElementById('startBtn').textContent='다시 도전'}
function start(){if(won){location.reload();return}if(dead){dead=false;document.getElementById('overlay').classList.add('hidden');P.x=checkpoint.x;P.y=checkpoint.y;P.hidden=false;P.stam=70;alert=22;section='복도';objective();return}started=true;document.getElementById('overlay').classList.add('hidden');toast('작전 시작. 소리를 내지 마라.',2200);objective()}
function hud(){document.getElementById('alertText').textContent=Math.round(alert)+'%';document.getElementById('alertFill').style.width=alert+'%';document.getElementById('stamText').textContent=Math.round(P.stam);document.getElementById('stamFill').style.width=P.stam+'%';document.getElementById('noiseText').textContent=Math.round(P.noise);document.getElementById('noiseFill').style.width=P.noise+'%'}
function update(dt){if(!started||paused||dead||won)return;cd=Math.max(0,cd-dt);let ix=(K.d||K.ArrowRight?1:0)-(K.a||K.ArrowLeft?1:0),iy=(K.s||K.ArrowDown?1:0)-(K.w||K.ArrowUp?1:0),moving=ix||iy;if(moving){let m=Math.hypot(ix,iy);ix/=m;iy/=m}let run=K.Shift&&P.stam>3&&moving,sp=P.speed*(run?1.72:1)*(P.hidden?.34:1);if(run)P.stam-=28*dt;else P.stam+=15*dt;P.stam=clamp(P.stam,0,100);move(P,ix*sp*dt,iy*sp*dt);if(moving&&!P.hidden)P.noise=clamp(P.noise+(run?70:28)*dt,0,100);else P.noise=Math.max(0,P.noise-75*dt);
for(const g of G){let a=g.route[Math.floor(g.i)%g.route.length],b=g.route[(Math.floor(g.i)+1)%g.route.length],dx=b[0]-g.x,dy=b[1]-g.y,dd=Math.hypot(dx,dy);if(dd<5)g.i=(g.i+.75*dt)%g.route.length;else{g.angle=Math.atan2(dy,dx);g.x+=dx/dd*g.speed*dt;g.y+=dy/dd*g.speed*dt}let v=sees(g,P,g.range,g.fov);if(P.hidden)v*=.12;if(v){alert+=g.rate*v*34*dt;if(alert>93)fail(g.name+'에게 완전히 발각되었다.')}if(P.noise>20&&Math.hypot(g.x-P.x,g.y-P.y)<190)alert+=P.noise*.012*dt}
for(const c of CAM){c.a+=c.spin*dt;let v=sees({x:c.x,y:c.y,angle:c.a},P,c.range,c.fov);if(v&&!P.hidden)alert+=18*v*dt}alert-= (P.hidden?10:3.2)*dt;alert=clamp(alert,0,100);if(alert>=100)fail('복도 전체에 경보가 울렸다.');if(hasSnack&&P.x<350&&P.y>650)win();sectionCheck();hud()}
function label(t,x,y){X.fillStyle='#2b3238';X.font='bold 16px monospace';X.fillText(t,x,y)}
function vision(o,f,r,cam=false){X.save();X.translate(o.x,o.y);X.rotate(o.angle);let gr=X.createRadialGradient(0,0,5,0,0,r);gr.addColorStop(0,cam?'rgba(255,100,80,.22)':'rgba(255,230,120,.18)');gr.addColorStop(1,'rgba(255,180,80,0)');X.fillStyle=gr;X.beginPath();X.moveTo(0,0);X.arc(0,0,r,-f/2,f/2);X.closePath();X.fill();X.restore()}
function guard(g){X.save();X.translate(g.x,g.y);X.fillStyle='#10192b';X.fillRect(-10,-10,20,24);X.fillStyle='#f0d2bd';X.beginPath();X.arc(0,-15,9,0,Math.PI*2);X.fill();X.fillStyle='#26385c';X.fillRect(-9,-23,18,6);X.restore()}
function player(){X.save();X.translate(P.x,P.y);X.globalAlpha=P.hidden?.42:1;X.fillStyle='#1d3557';X.fillRect(-9,-9,18,22);X.fillStyle='#f0d2bd';X.beginPath();X.arc(0,-14,8,0,Math.PI*2);X.fill();X.fillStyle='#263b66';X.fillRect(-9,-21,18,5);X.fillStyle='#f1c84b';X.fillRect(-6,-3,12,4);X.restore()}
function itemKey(x,y){X.fillStyle='#ffd86a';X.beginPath();X.arc(x,y,10,0,Math.PI*2);X.fill();X.strokeStyle='#5b4a1f';X.lineWidth=4;X.beginPath();X.moveTo(x+8,y);X.lineTo(x+30,y);X.lineTo(x+30,y+8);X.stroke();X.fillStyle='#fff0a6';X.font='bold 12px monospace';X.fillText('KEY',x-13,y-18)}
function snack(x,y){X.fillStyle='#e9c17a';X.fillRect(x-28,y-18,56,36);X.strokeStyle='#7a4d30';X.strokeRect(x-28,y-18,56,36);X.fillStyle='#d54b4b';X.font='bold 12px monospace';X.fillText('SNACK',x-21,y+4)}
function arrow(x,y){let a=Math.atan2(y-P.y,x-P.x),dd=Math.hypot(x-P.x,y-P.y);if(dd<100)return;X.save();X.translate(P.x+Math.cos(a)*45,P.y+Math.sin(a)*45);X.rotate(a);X.fillStyle='#ffd76b';X.beginPath();X.moveTo(14,0);X.lineTo(-8,-7);X.lineTo(-3,0);X.lineTo(-8,7);X.closePath();X.fill();X.restore()}
function draw(){X.clearRect(0,0,W,H);X.fillStyle='#909a9f';X.fillRect(0,0,W,H);X.strokeStyle='#7c878c';X.lineWidth=1;for(let x=20;x<W;x+=40){X.beginPath();X.moveTo(x,110);X.lineTo(x,855);X.stroke()}for(let y=135;y<H;y+=40){X.beginPath();X.moveTo(20,y);X.lineTo(1260,y);X.stroke()}
X.fillStyle='#aab0b3';X.fillRect(35,130,360,700);X.fillStyle='#9ca6aa';X.fillRect(420,130,360,275);X.fillStyle='#9aa5aa';X.fillRect(805,130,440,275);X.fillStyle='#8f999e';X.fillRect(420,430,825,400);for(const q of walls){X.fillStyle='#343b42';X.fillRect(q.x,q.y,q.w,q.h);X.fillStyle='#555e65';X.fillRect(q.x,q.y,q.w,5)}for(const q of doors){X.fillStyle=q.open?'#3b8f62':'#7d3030';X.fillRect(q.x,q.y,q.w,q.h)}label('교실',75,165);label('학생부실',535,165);label('정보실',970,165);label('복도',610,465);for(const o of obs){X.fillStyle=o.t==='desk'?'#4f5960':o.t==='locker'?'#58636a':'#555e65';X.fillRect(o.x,o.y,o.w,o.h);X.fillStyle='#7d878c';X.fillRect(o.x,o.y,o.w,5);if(o.t==='desk'){X.fillStyle='#2e3439';X.fillRect(o.x+12,o.y+10,o.w-24,5)}}if(!hasKey)itemKey(630,350);if(hasKey&&!hasSnack)snack(1090,330);for(const o of obs)if(d(P,{x:o.x+o.w/2,y:o.y+o.h/2})<68){X.strokeStyle='#b7d8ff88';X.setLineDash([5,5]);X.strokeRect(o.x-5,o.y-5,o.w+10,o.h+10);X.setLineDash([])}for(const g of G)vision(g,g.fov,g.range);for(const c of CAM)vision({x:c.x,y:c.y,angle:c.a},c.fov,c.range,true);for(const g of G)guard(g);player();if(!hasKey)arrow(630,350);else if(!hasSnack)arrow(1090,330);else arrow(145,755)}
function loop(t){let dt=Math.min(.035,(t-last)/1000||0);last=t;update(dt);draw();requestAnimationFrame(loop)}requestAnimationFrame(loop);
window.onkeydown=e=>{K[e.key]=true;if([' ','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.key))e.preventDefault();if((e.key==='e'||e.key==='E')&&!e.repeat)interact();if(e.key===' '&&!e.repeat)hide();if(e.key==='Escape'&&!dead&&!won){paused=!paused;toast(paused?'⏸ 일시정지':'▶ 재개')}};window.onkeyup=e=>K[e.key]=false;
document.querySelectorAll('[data-key]').forEach(b=>{let k=b.dataset.key;let dn=e=>{e.preventDefault();K[k]=true},up=e=>{e.preventDefault();K[k]=false};b.addEventListener('pointerdown',dn);b.addEventListener('pointerup',up);b.addEventListener('pointercancel',up);b.addEventListener('pointerleave',up)});
document.getElementById('startBtn').onclick=start;document.getElementById('pauseBtn').onclick=()=>{paused=!paused;toast(paused?'⏸ 일시정지':'▶ 재개')};document.getElementById('restartBtn').onclick=()=>location.reload();objective();hud();
</script></div></body></html>'''

components.html(HTML, height=940, scrolling=False)
